language: php
php:
  - '7.0'
  - nightly

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install

script: phpunit

install:
  - ./bin/ci/install_dependencies.sh
  - php vendor/vendors.php